apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      color: blue
  template:
    metadata:
      labels:
        app: product-service
        color: blue
    spec:
      containers:
        - name: product
          image: shaligatv/product-service
          ports:
            - containerPort: 3000
