apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      color: green
  template:
    metadata:
      labels:
        app: product-service
        color: green
    spec:
      containers:
        - name: product-container
          image: shaliga/car-image:{{TAG}}  # Jenkins ൽ TAG മാറ്റം വരും
          ports:
            - containerPort: 3000
                                       
