apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-blue
  labels:
    app: product-service
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
      color: blue
  template:
    metadata:
      labels:
        app: product-service
        color: blue
    spec:
      containers:
      - name: product-service
        image: shaliga/product-service:45
        ports:
        - containerPort: 8080
