apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # optional: or remove this line to let Kubernetes assign automatically
  type: NodePort
