apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
    color: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
