apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-blue         # consistent naming pattern with green (user-green, user-blue)
spec:
  replicas: 2             # same replicas as green
  selector:
    matchLabels:
      app: user           # same app label as green
      color: blue         # color changed only
  template:
    metadata:
      labels:
        app: user
        color: blue
    spec:
      containers:
      - name: user        # same container name as green
        image: shaliga/user-service:45
        ports:
        - containerPort: 3000   # same port as green deployment
