apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      color: green  # ✅ Ensure this matches below
  template:
    metadata:
      labels:
        app: user
        color: green  # ✅ Must match selector above
    spec:
      containers:
        - name: user
          image: shaliga/user-service:18
          ports:
            - containerPort: 3000
