apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
  labels:
    app: user-service
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
      color: blue
  template:
    metadata:
      labels:
        app: user-service
        color: blue
    spec:
      containers:
      - name: user-service
        image: shaliga/user-service:45
        ports:
        - containerPort: 8080
