apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-blue
  labels:
    app: product
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
      color: blue
  template:
    metadata:
      labels:
        app: product
        color: blue
    spec:
      containers:
      - name: product
        image: shaliga/product-service:18
        ports:
        - containerPort: 8080
