apiVersion: v1
kind: Service
metadata:
  name: product     # ✅ Stable service name (NOT color-specific)
spec:
  selector:
    app: product
    color: blue     # ✅ Initially point to blue deployment
  ports:
    - port: 80
      targetPort: 8080
