apiVersion: v1
kind: Service
metadata:
  name: product-green-nodeport
spec:
  selector:
    app: product
    color: green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003
  type: NodePort
