# ecommerce-microservices/kubernetes/product/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: default
spec:
  selector:
    app: product
    color: blue  # initial value; will be patched later to green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
