apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-app
  type: NodePort  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31001  
