apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-container
        image: shaliga/user-service:latest  # e.g., shaliga/user-app:latest
        ports:
        - containerPort: 3000
