apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app  # this label should match your pod's labels
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
