# ecommerce-microservices/kubernetes/user/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: default
spec:
  selector:
    app: user
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
