apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      color: blue
  template:
    metadata:
      labels:
        app: user-service
        color: blue
    spec:
      containers:
        - name: user
          image: shaligatv/user-service
          ports:
            - containerPort: 3000
