apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081  # You can change or omit this for random port
  type: NodePort
