apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort    # Changed from ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081   # Optional: specify NodePort in allowed range 30000-32767
  selector:
    app: user-service
    color: green     # Active color controlled by pipeline (blue or green)
